settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('twc/', include("twitterCloneApp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns 에 이미지로 접근하는 주소 추가: static(통과시키는 url, document_root=실제 연결할 저장장소)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitterCloneApp/urls.py
from django.urls import path
from . import twuser_views, twtweet_views
urlpatterns = [
    path('', twuser_views.main, name='main'),
    # twUser
    path('join/', twuser_views.join, name='join'),
    path('login/', twuser_views.user_login, name='login'),
    path('activate/<str:uidb64>/<str:token>/', twuser_views.activate, name='activate'),
    path('logout/', twuser_views.logout, name='logout'),
    path('profile/<str:id>', twuser_views.profile, name='profile'),
    path('setting/profile', twuser_views.edit_profile, name='edit_profile'),

    # twTweet
    path('home/', twtweet_views.get_list, name='home'),
    path('tweet/', twtweet_views.tweet, name='tweet'),
    path('update/<int:id>/', twtweet_views.update, name='update'),
    path('delete/<int:id>/', twtweet_views.delete, name='delete'),




]

app_name = 'twc'

twitterCloneSettings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('twc/', include("twitterCloneApp.urls")),
]

twitterCloneApp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from twitterCloneApp.authmodel import TwUser
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit


class TwFollowUser(models.Model):
    # follow_sno = models.IntegerField() # id가 있는데 이게 필요할까?
    # Many to One Relation: Foreign key 설정
    user = models.ForeignKey(TwUser, on_delete=models.CASCADE, related_name="TwFollowUser_user_id", error_messages=None)            # PK = FK (identifying-relation)
    following_user = models.ForeignKey(TwUser, on_delete=models.CASCADE, default=None, null=True, related_name="following_user_id")  # PK != FK (Non-identifying-relation)
    follower_user = models.ForeignKey(TwUser, on_delete=models.CASCADE, default=None, null=True, related_name="follower_user_id")   # PK != FK (Non-identifying-relation)
    data_del_yn = models.CharField(max_length=1, default="N")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class TwTweet(models.Model):
    tw_psno = models.IntegerField(null=True)
    # FK 가 user_id 가 아니라 user_id_id 로 잡혀서 renaming 함
    user = models.ForeignKey(TwUser, on_delete=models.CASCADE, related_name="TwUser_user_id", error_messages=None)
    tw_content = models.CharField(max_length=500, null=False)
    image = models.ImageField(
        upload_to='img/',
        # processors=[ResizeToFit(width=960, upscale=False)],
        # format='JPEG',
        blank=True, null=True
    )
    # 공통컬럼
    data_del_yn = models.CharField(max_length=1, default="N")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    REQUIRED_FIELDS = ['user', 'tw_content']
#     https://velog.io/@magnoliarfsit/ReDjango-8.-QuerySis%20named%20as%20the%20'USERNAME_FIELD',%20but%20it%20is%20not%20unique.et-Method-4


# 이미지 업로드 : 참조) https://the-boxer.tistory.com/41
# 멀티파일 업로드 : 참조) https://stackoverflow.com/questions/34006994/how-to-upload-multiple-images-to-a-blog-post-in-django
class TwImages(models.Model):
    tweet = models.ForeignKey(TwTweet, blank=False, null=False, related_name="tweet_sno", on_delete=models.CASCADE)
    # save resized version
    image = models.ImageField(upload_to='img/', blank=True, null=True)
    # image = models.ImageField(
    #     upload_to='img/',
    #     processors=[ResizeToFit(width=960, upscale=False)],
    #     format='JPEG',
    #     blank=True, null=True
    # )
    # - ProcessedImageField: django-orm이 인식하는 처리된 이미지 속성. image필드와 마찬가지로, 이미지가 저장된 위치를 DB에 저장
    # - ImageSpecField: 이미 생성된 이미지의 캐시용 이미지를 생성


class TwAct(models.Model):
    tw_act_sno = models.IntegerField()
    user = models.ForeignKey(TwTweet, on_delete=models.CASCADE, related_name="TwAct_user_id", error_messages=None)
    rt_user = models.ForeignKey(TwUser, on_delete=models.CASCADE, null=True, related_name="rt_user_id")
    qt_user = models.ForeignKey(TwUser, on_delete=models.CASCADE, null=True, related_name="qt_user_id")
    like_user = models.ForeignKey(TwUser, on_delete=models.CASCADE, null=True, related_name="like_user_id")
    data_del_yn = models.CharField(max_length=1, default="N")



# 모델 생성/수정 후 마이그레이션
# python manage.py makemigrations (appname)
# python manage.py migrate
# python manage.py dbshell

twitterCloneApp/forms.py
from django import forms
from django.forms import ModelForm
from twitterCloneApp.authmodel import TwUser
from twitterCloneApp.models import TwTweet, TwImages
from django.utils.translation import gettext_lazy as _


class TwJoinForm(ModelForm):
    class Meta:

        model = TwUser
        fields = ['user_id', 'user_nm', 'user_email', 'user_pwd']
        labels = {
            'user_id': _('아이디')
            , 'user_nm': _('이름')
            , 'user_email': _('이메일 주소')
            , 'user_pwd': _('비밀번호')
        }
        # help_text = {
        #     'user_id': _('아이디를 입력해주세요. ')
        #     , 'user_nm': _('이름을 입력해주세요. ')
        #     , 'user_email': _('이메일 주소를 입력해주세요. ')
        #     , 'user_pwd': _('비밀번호를 입력해주세요. ')
        # }
        widgets = {
            'user_id': forms.TextInput(attrs={'class': 'form-control'})
            , 'user_nm': forms.TextInput(attrs={'class': 'form-control'})
            , 'user_pwd': forms.PasswordInput(attrs={'class': 'form-control'})
            , 'user_email': forms.EmailInput(attrs={'class': 'form-control'})
        }
        # error_messages = {
        #     'user_id': _('아이디는 최대 30자로 설정 가능합니다. ')
        #     , 'user_nm': _('이름은 최대 15자로 설정 가능합니다.  ')
        #     , 'user_email': _('이메일 형식이 잘못되었습니다. ')
        #     , 'user_pwd': _('비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.')
        # }


class TwLoginForm(ModelForm):
    class Meta:

        model = TwUser
        fields = ['user_id', 'user_pwd']
        labels = {
            'user_id': _('아이디')
            , 'user_pwd': _('비밀번호')
        }
        # help_text = {
        #     'user_id': _('아이디를 입력해주세요. ')
        #     , 'user_pwd': _('비밀번호를 입력해주세요. ')
        # }
        widgets = {
            'user_id': forms.TextInput(attrs={'class': 'form-control'})
            , 'user_pwd': forms.PasswordInput(attrs={'class': 'form-control'})
        }
        # error_messages = {
        #     'user_id': _('아이디는 최대 30자로 설정 가능합니다. ')
        #     , 'user_pwd': _('비밀번호를 입력해주세요. ')
        # }


class TwUserProfileForm(ModelForm):
    class Meta:
        model = TwUser
        fields = ['user_nm', 'user_birthday', 'user_acc_pub_yn']

        labels = {
            'user_nm': _('닉네임')
            # , 'user_prof_pic': _('이미지 url')
            # , 'user_prof_bio': _('바이오 이미지 url')
            , 'user_birthday': _('생년월일')
            , 'user_acc_pub_yn': _('계정 공개 여부')
        }
        widgets = {
            'user_nm': forms.TextInput(attrs={'class': 'form-control'})
            , 'user_birthday': forms.TextInput(attrs={'class': 'form-control'})
            , 'user_acc_pub_yn': forms.CheckboxInput()
        }


class TwTweetForm(ModelForm):
    class Meta:
        model = TwTweet
        fields = ['user', 'tw_content']
        labels = {

        }
        widgets = {
            'user': forms.HiddenInput(),
        }


class TwImageForm(ModelForm):
    image = forms.ImageField(label='이미지')

    class Meta:
        model = TwImages
        fields = ('image',)

twitterCloneApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
# 로그인 인증 관련
from twitterCloneApp.authmodel import TwUser
from twitterCloneApp.mybackends import MyBackend
# 이메일 인증 관련
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
from twitterCloneApp.token import account_active_token
from twitterCloneApp.forms import TwJoinForm, TwLoginForm, TwTweetForm
from django.db.models import Count, Avg
from twitterCloneApp.models import TwTweet
# ====================================================================================================================================

mybackend = MyBackend()


# Create your views here.
def main(request):
    print(request.session.get('user_id'))
    context = {}
    return render(request, 'twc/main.html', context)


def join(request):
    if request.method == 'GET':
        join_form = TwJoinForm()
        return render(request, 'twc/join.html', {'form': join_form})
    elif request.method == 'POST':
        join_form = TwJoinForm(request.POST)
        if join_form.is_valid():
            user = TwUser.objects.create_user(**join_form.cleaned_data)
            user.is_active = False # 이메일 인증 전 유저 비활성화
            user.save()

            current_site = get_current_site(request)
            message = render_to_string('twc/activation_email.html', {
                'user': user,
                'domain': current_site.domain, # 127.0.0.1:8000
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_active_token.make_token(user) # 토큰값 생성
            })

            mail_title = '회원가입 인증 메일'
            mail_to = request.POST['user_email']
            email = EmailMessage(mail_title, message, to=[mail_to])
            email.send()

            return redirect('twc:main')


def user_login(request):
    if request.method == 'GET':
        login_form = TwLoginForm()
        return render(request, 'twc/login.html', {'form': login_form})
    elif request.method == 'POST':
        login_form = TwLoginForm(request.POST)
        user_id = request.POST['user_id']
        user_pwd = request.POST['user_pwd']
        user = mybackend.authenticate(request, user_id, user_pwd)
        if user is not None and user.is_active:     # 로그인 인증 & 이메일 인증 완료 -> 로그인 성공
            mybackend.get_user(user_id)
            request.session['id'] = user.id
            request.session['user_id'] = user_id
            return redirect('twc:home')
        else:                                        # 로그인 실패
            return redirect('twc:login')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = TwUser.objects.get(pk=uid)

    except(TypeError, ValueError, OverflowError): # TwUser.DoesNotExist
        user = None

    if user is not None and account_active_token.check_token(user, token):       # 토큰값 일치 여부 확인
        user.is_active = True
        user.save()
        mybackend.get_user(user.user_id)
        request.session['id'] = user.id
        request.session['user_id'] = user.user_id
        return redirect('twc:home')

    else:
        return render(request, 'twc/main.html', {'error': '계정 활성화 오류'})
    return


def logout(request):
    del request.session['id']
    del request.session['user_id']
    request.session.modified = True # depending on settings
    return redirect('twc:main')


# tweet CRUD ======================================================================================================
def list(request):
    id = request.session.get('id')
    # tlqkf 이게 어떻게 되는거야 어떻게 알고 TwTweet.user_id(number)로 조인해서 TwUser.user_id(string) 을 가져오는거임
    tw_list = TwTweet.objects.filter(user_id=id).select_related().all()

    return render(request, 'twc/home.html', {'list': tw_list})


def tweet(request):
    if request.method == 'GET':
        form = TwTweetForm()
        return render(request, 'twc/tweet.html', {'form': form})
    elif request.method == 'POST':
        form = TwTweetForm(request.POST)
        if form.is_valid():
            print(form)
            form.save(commit=True)
            return redirect('twc:home')
    return


def update(request, id):
    item = get_object_or_404(TwTweet, pk=id)
    if request.method == 'GET':
        form = TwTweetForm(instance=item)
        return render(request, 'twc/update.html', {'form': form, 'id': item.id})
    elif request.method == 'POST':
        form = TwTweetForm(request.POST, instance=item)
        if form.is_valid():
            item = form.save(commit=True)
        return redirect('twc:home')


def delete(request, id):
    item = get_object_or_404(TwTweet, pk=id)
    item.delete()
    return redirect('twc:home')

# ORM 테이블 조인 : https://brownbears.tistory.com/101
# Queryset 조작 명령어: https://velog.io/@gandalfzzing/Django-%EC%BF%BC%EB%A6%AC%EC%85%8B-%EC%A1%B0%EC%9E%91-%EB%AA%85%EB%A0%B9%EC%96%B4%EB%93%A4

twitterCloneApp/templates/twc/activation_email.html
<div>
    {{ user.user_id }}님, 아래 링크를 클릭하여 계정을 활성화하세요:
    http://{{domain}}{% url 'twc:activate' uid token %}
</div>

twitterCloneApp/templates/twc/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Twitter Clone - ReTTiwT </title>
    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!-- jQuery for Ajax   -->
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
</head>
<body>
 {% if request.session.user_id %}
    <nav class="nav nav-pills flex-column flex-sm-row">
        <a class="flex-sm-fill text-sm-center nav-link active" href="{% url 'twc:home' %}"> Home </a>
        <a class="flex-sm-fill text-sm-center nav-link" href="#">Explore</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="#">Notifications</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="#">Messages</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="#">Bookmarks</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'twc:profile' id=request.session.user_id %}">Profile</a>
        <a class="flex-sm-fill text-sm-center nav-link disabled" href="#" tabindex="-1" aria-disabled="true">More</a>
        <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'twc:tweet' %}"><div class="btn btn-primary">Tweet</div></a>
        <a class="flex-sm-fill text-sm-center nav-link" href="{% url 'twc:logout' %}"><div class="btn btn-danger">Logout</div></a>
    </nav>
 {% endif %}

    <section>
        {% block content %}
        {% endblock %}
    </section>


</body>

</html>

twitterCloneApp/templates/twc/edit_profile.html
{% extends 'twc/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <form action="{% url 'twc:edit_profile' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label> 아이디 </label>
            <input type="text" name="user_id" id="user_id" class="" readonly>
        </div>

        <div>
            <label> 닉네임 </label> 
            <input type="text" name="user_nm" class="">
        </div>
        
        <div class="form-group">
            <label for="exampleFormControlSelect1"> 생년월일 </label>
            <select class="form-control" name="byear" id="exampleFormControlSelect1">
                <option>1990</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
            </select>

            <select class="form-control" name="bmonth" id="exampleFormControlSelect1">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
            </select>

            <select class="form-control" name="bday" id="exampleFormControlSelect1">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
            </select>
        </div>
        
        <div>
            <label> 계정 공개 </label> 
            <input type="checkbox" name="user_acc_pub_yn" class="">
        </div>
        
        <div class="form-group">
            <label for="exampleFormControlFile1"> 프로필 사진 </label>
            <input type="file" class="form-control-file" id="exampleFormControlFile1" name="image1">
        </div>

        <div class="form-group">
            <label for="exampleFormControlFile2"> 바이오 사진 </label>
            <input type="file" class="form-control-file" id="exampleFormControlFile2" name="image2">
        </div>

        <button type="submit" class="btn btn-primary"> 정보 수정 </button>

    </form>
</div>

<script>
    let user_id = document.getElementById("user_id")
    user_id.value = '{{ request.session.id}}'
    console.log(user_id.value);

</script>
{% endblock %}

twitterCloneApp/templates/twc/edit_profileform.html
{% extends 'twc/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <form action="{% url 'twc:edit_profile' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_p }}
            <input type="file" name="images1">
            <input type="file" name="images2">
        </table>
        <button type="submit" class="btn btn-primary"> 정보 수정 </button>

    </form>
</div>

<script>
    let user_id = document.getElementById('{{ form.id.id_for_label }}')
    user_id.value = '{{ request.session.id}}'
    console.log(user_id.value);

</script>
{% endblock %}

twitterCloneApp/templates/twc/home.html
{% extends 'twc/base.html' %}
{% load static %}
{% block content %}

<div class="">
    {% for tweet in list %}
    <div class="media">
        <img src="/media/{{tweet.user_prof_pic}}" class="mr-3 rounded-lg" alt="...">
        <div class="media-body">
            <h5 class="mt-0"> {{ tweet.user_nm }}
                <span>@{{ tweet.user }}</span>
            </h5>
            {{ tweet.tw_content }}
        {% if tweet.image %}
            <img src="/media/{{ tweet.image }}">
        {% endif %}
            <p>{{ tweet.updated_at|date:"Y-m-d" }}</p>
        {% if request.session.id == tweet.user_id %}
            <a href="{% url 'twc:update' id=tweet.id %}">
                <button type="submit" class="btn btn-info"> 수정하기 </button>
            </a>
            <a href="{% url 'twc:delete' id=tweet.id %}">
                <button type="submit" class="btn btn-danger"> 삭제하기 </button>
            </a>
        {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

twitterCloneApp/templates/twc/join.html
{% extends 'twc/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <form id="join_form" name="join_form" action="{% url 'twc:join' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputId1"> 아이디 * </label>
            <input type="text" name="user_id" class="form-control" id="exampleInputId1" aria-describedby="idHelp" >
            <small id="idHelp" class="form-text text-muted">ex) gildong123</small>
        </div>

        <div class="form-group">
            <label for="exampleInputName1"> 닉네임 * </label>
            <input type="text" name="user_nm" class="form-control" id="exampleInputName1" aria-describedby="nameHelp" >
            <small id="nameHelp" class="form-text text-muted">ex) 길동 </small>
        </div>
        
        <div class="form-group">
            <label for="exampleInputEmail1"> 이메일 * </label>
            <input type="email" name="user_email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" >
            <small id="emailHelp" class="form-text text-muted">ex) gildong@gmail.com</small>
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">비밀번호 * </label>
          <input type="password" name="user_pwd" class="form-control" id="exampleInputPassword1">
          <small id="passwordHelp" class="form-text text-muted"> 영문+숫자 조합, 8자리 이상 </small>
        </div>

        <button type="button" class="btn btn-primary btn_submit"> 가입 </button>
    </form>
</div>
<script src="{% static 'js/join.js' %}"></script>
{% endblock %}

twitterCloneApp/templates/twc/login.html
{% extends 'twc/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <form id="login_form" name="login_form" action="{% url 'twc:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputId1"> 아이디 </label>
            <input type="text" name="user_id" class="form-control" id="exampleInputId1" placeholder="아이디를 입력하세요. ">
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1">비밀번호 * </label>
            <input type="password" name="user_pwd" class="form-control" id="exampleInputPassword1" placeholder="비밀번호를 입력하세요. ">
        </div>

        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1"> 로그인 유지 </label>
        </div>
        
        <span><strong> {{ error }} </strong> </span>
        <button type="button" class="btn btn-primary btn_submit"> 로그인 </button>
    </form>
</div>
<script src="{% static 'js/login.js' %}"></script>
{% endblock %}

twitterCloneApp/templates/twc/main.html
{% extends 'twc/base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <h3>Welcome to ReTTiwT ! </h3>

    <a class="btn btn-primary" href="{% url 'twc:join' %}" role="button">
        <div>
            <span> 가입하기 </span>
        </div>
    </a>
    <a class="btn btn-secondary" href="{% url 'twc:login' %}" role="button">
         <div>
             <span> 로그인 </span>
         </div>
    </a>
{% endblock %}

twitterCloneApp/templates/twc/profile.html
{% extends 'twc/base.html' %}
{% load static %}
{% block content %}
    <div class="card mb-3">
      <img src="{% static 'img/background1.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{ user.user_id }}</h5>  {{ user.user_nm }}
        <p class="card-text">{{ user.user_email }} </p>
          <p> profile <img src="/media/{{ user.user_prof_pic}}"></p>
          <p> bio <img src="/media/{{ user.user_prof_bio}}"></p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          <a href="{% url 'twc:edit_profile' %}"><button type="submit" class="btn btn-info"> 정보 수정 </button></a>
      </div>
    </div>
{% endblock %}

twitterCloneApp/templates/twc/tweet.html
{% extends 'twc/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <form name="tweet_form" id="tweet_form" action="{% url 'twc:tweet' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="user" id="user_id">
        <div class="form-group">
            <label for="exampleFormControlTextarea1"></label>
            <textarea name="tw_content" class="form-control tw_content" id="exampleFormControlTextarea1" rows="3" maxlength="140"></textarea>
        </div>
        
        <div class="form-group">
            <label for="exampleFormControlFile1"></label>
            <input type="file" name="image" class="form-control-file" id="exampleFormControlFile1" multiple>
        </div>
       
        <button type="button" class="btn btn-primary btn_submit"> 글쓰기 </button>
    </form>
</div>
<script src="{% static 'js/tweet.js' %}"></script>
<script>
    let user_id = document.querySelector('#user_id');
    user_id.value = `{{ request.session.id}}`
    console.log(user_id.value);

</script>
{% endblock %}

twitterCloneApp/templates/twc/tweet2.html
{% extends 'twc/base.html' %}
{% load static %}
<div class="container">
    <form action="{% url 'twc:tweet' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="user" class="">
        <div>
            <textarea name="tw_content" class="" maxlength="140"></textarea>
        </div>
        <!--imageform 사용해서 multiple 하고 싶은데.. 구글링해도 1개를 여러번 올리는 방법밖에 안나와서 일단..-->
        <div>
            <input type="file" name="images" multiple>
        </div>
        <button type="submit" class="btn btn-primary"> 글쓰기 </button>
    </form>
</div>

<script>
    let user_id = document.getElementById('{{ form.user.id_for_label }}')
    user_id.value = '{{ request.session.id}}'
    console.log(user_id.value);

</script>

twitterCloneApp/templates/twc/update.html
{% extends 'twc/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <form id="update_form" name="update_form" action="{% url 'twc:update' id=id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="user" id="user_id" value="{{ form.user.value }}">
        <div class="form-group">
            <label for="exampleFormControlTextarea1"></label>
            <textarea name="tw_content" class="form-control tw_content" id="exampleFormControlTextarea1" rows="3" maxlength="140">{{form.tw_content.value}}</textarea>
        </div>

        <div class="form-group">
            <label for="exampleFormControlFile1"></label>
            <input type="file" name="image" class="form-control-file" id="exampleFormControlFile1" multiple>
            {{ image }} <!--input type file 은 readonly -->
        </div>

        <button type="button" class="btn btn-primary btn_submit"> 글수정 </button>
    </form>
</div>
<script src="{% static 'js/tweet.js' %}"></script>
{% endblock %}